data_compare_check: FAIL
Details: the data mismatches are: [{'customer_id': Decimal('5'), 'first_name': 'Liam', 'last_name': 'Williams', 'email': 'liam.williams@example.com', 'created_at': datetime.datetime(2025, 3, 5, 12, 48, 23), 'origin': 'source_record'}, {'customer_id': Decimal('2'), 'first_name': 'Alice', 'last_name': 'Smith', 'email': 'alice.smith@example.com', 'created_at': datetime.datetime(2025, 3, 5, 12, 48, 23), 'origin': 'source_record'}, {'customer_id': Decimal('1'), 'first_name': 'John', 'last_name': 'Doe', 'email': 'john.doe@example.com', 'created_at': datetime.datetime(2025, 3, 5, 12, 48, 23), 'origin': 'source_record'}, {'customer_id': Decimal('4'), 'first_name': 'Emma', 'last_name': 'Brown', 'email': 'emma.brown@example.com', 'created_at': datetime.datetime(2025, 3, 5, 12, 48, 23), 'origin': 'source_record'}, {'customer_id': Decimal('3'), 'first_name': 'Bob', 'last_name': 'Johnson', 'email': 'bob.johnson@example.com', 'created_at': datetime.datetime(2025, 3, 5, 12, 48, 23), 'origin': 'source_record'}]

